"use client";

import {
  ApartmentOutlined,
  AppstoreOutlined,
  BankOutlined,
  BarChartOutlined,
  BellOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  ClusterOutlined,
  CarryOutOutlined,
  CheckCircleFilled,
  CheckCircleOutlined,
  CheckOutlined,
  CloseCircleFilled,
  DashboardOutlined,
  DatabaseOutlined,
  AuditOutlined,
  BranchesOutlined,
  DeleteOutlined,
  EnvironmentOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FieldTimeOutlined,
  FileTextOutlined,
  FilterOutlined,
  FolderOpenOutlined,
  HistoryOutlined,
  IdcardOutlined,
  InfoCircleFilled,
  KeyOutlined,
  LinkOutlined,
  LockOutlined,
  PictureOutlined,
  ProfileOutlined,
  QuestionCircleOutlined,
  ReloadOutlined,
  ScheduleOutlined,
  SafetyCertificateOutlined,
  SettingOutlined,
  SolutionOutlined,
  TeamOutlined,
  UnorderedListOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  WalletOutlined,
  ToolOutlined,
  WarningFilled,
  WarningOutlined,
} from "@ant-design/icons";

const ICONS = {
  "navigation:dashboard": DashboardOutlined,
  "navigation:master-data": DatabaseOutlined,
  "navigation:organization": BankOutlined,
  "navigation:location": EnvironmentOutlined,
  "navigation:organization-unit-type": ClusterOutlined,
  "navigation:organization-unit": BranchesOutlined,
  "navigation:position": SolutionOutlined,
  "navigation:employment-type": ProfileOutlined,
  "navigation:employees": TeamOutlined,
  "navigation:employee-data": IdcardOutlined,
  "navigation:leave": CalendarOutlined,
  "navigation:reports": BarChartOutlined,
  "navigation:expiring-contract": FileTextOutlined,
  "navigation:retirement-projection": FieldTimeOutlined,
  "navigation:disciplinary-report": AuditOutlined,
  "navigation:access": KeyOutlined,
  "navigation:organization-account": UserSwitchOutlined,
  "navigation:organization-settings": SettingOutlined,
  "navigation:leave-settings": ScheduleOutlined,
  "navigation:disciplinary-settings": SafetyCertificateOutlined,
  "navigation:retirement-policy": ClockCircleOutlined,
  "navigation:system-maintenance": ToolOutlined,
  "navigation:storage-maintenance": FolderOpenOutlined,
  "solar:widget-5-bold-duotone": AppstoreOutlined,
  "solar:database-bold-duotone": DatabaseOutlined,
  "solar:buildings-2-bold-duotone": BankOutlined,
  "solar:buildings-3-bold-duotone": BankOutlined,
  "solar:map-point-wave-bold-duotone": EnvironmentOutlined,
  "solar:case-round-bold-duotone": CarryOutOutlined,
  "solar:document-add-bold-duotone": FileAddOutlined,
  "solar:users-group-rounded-bold-duotone": TeamOutlined,
  "fa6-solid:people-group": TeamOutlined,
  "solar:user-id-bold-duotone": IdcardOutlined,
  "solar:calendar-mark-bold-duotone": CalendarOutlined,
  "solar:calendar-date-bold-duotone": CalendarOutlined,
  "solar:calendar-minimalistic-bold-duotone": CalendarOutlined,
  "solar:calendar-search-bold-duotone": CalendarOutlined,
  "solar:calendar-add-bold-duotone": CalendarOutlined,
  "solar:calendar-remove-bold-duotone": CalendarOutlined,
  "solar:chart-2-bold-duotone": BarChartOutlined,
  "solar:chart-bold-duotone": BarChartOutlined,
  "solar:chart-square-bold-duotone": BarChartOutlined,
  "clarity:contract-solid": FileTextOutlined,
  "solar:document-text-bold-duotone": FileTextOutlined,
  "solar:clipboard-list-bold-duotone": UnorderedListOutlined,
  "solar:checklist-minimalistic-bold-duotone": UnorderedListOutlined,
  "solar:clipboard-remove-bold-duotone": DeleteOutlined,
  "solar:shield-warning-bold-duotone": WarningOutlined,
  "solar:shield-check-bold-duotone": SafetyCertificateOutlined,
  "solar:shield-user-bold-duotone": SafetyCertificateOutlined,
  "solar:key-bold-duotone": KeyOutlined,
  "solar:key-minimalistic-square-3-bold-duotone": KeyOutlined,
  "solar:settings-bold-duotone": SettingOutlined,
  "solar:settings-minimalistic-bold-duotone": SettingOutlined,
  "solar:folder-with-files-bold-duotone": FolderOpenOutlined,
  "solar:structure-bold-duotone": ApartmentOutlined,
  "solar:user-linear": UserOutlined,
  "solar:lock-keyhole-linear": LockOutlined,
  "solar:lock-password-bold-duotone": LockOutlined,
  "solar:eye-linear": EyeOutlined,
  "solar:eye-closed-linear": EyeInvisibleOutlined,
  "solar:link-circle-bold-duotone": LinkOutlined,
  "solar:verified-check-bold-duotone": CheckCircleOutlined,
  "solar:user-check-rounded-bold-duotone": CheckCircleOutlined,
  "solar:user-block-rounded-bold-duotone": UserDeleteOutlined,
  "solar:check-circle-bold": CheckCircleFilled,
  "solar:close-circle-bold": CloseCircleFilled,
  "solar:danger-triangle-bold": WarningFilled,
  "solar:danger-triangle-bold-duotone": WarningOutlined,
  "solar:info-circle-bold": InfoCircleFilled,
  "solar:history-bold-duotone": HistoryOutlined,
  "solar:check-read-bold-duotone": FileDoneOutlined,
  "solar:bell-bing-bold-duotone": BellOutlined,
  "solar:refresh-linear": ReloadOutlined,
  "solar:restart-linear": ReloadOutlined,
  "solar:filter-bold-duotone": FilterOutlined,
  "solar:wallet-money-bold-duotone": WalletOutlined,
  "solar:gallery-wide-bold-duotone": PictureOutlined,
};

export default function AppIcon({
  icon,
  width,
  height,
  fontSize,
  color,
  style,
  ...props
}) {
  const IconComponent = ICONS[icon] || QuestionCircleOutlined;
  const size = fontSize ?? width ?? height;
  return (
    <IconComponent
      {...props}
      style={{
        ...(size ? { fontSize: size } : null),
        ...(color ? { color } : null),
        ...style,
      }}
    />
  );
}
